name: Deploy

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Installing dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy to server
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_SERVER }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./"
          dist_target_dir: "versions/${{ github.sha }}"
          delete: "true"
          exclude: "'^logs/' '^README.md' '^node_modules/'"